### ISSUE TITLE
print_taxon redundant?

### ISSUE THREAD

**Issue by mccalluc** [sckott/pytaxa#7]
- `print_taxon` is defined 3 times: Twice as a static method, and once as an instance method. The static methods are identical, but they do not produce the same result as the instance method: Would it make sense to just use the instance method everywhere?
- The one instance method just wraps repr, so I'm not sure that it's even necessary, really.

Sorry if this is confused.

**Comment by sckott** [comment]
Good question @mccalluc 

The instance method in `Taxon` is different from the other two, so I think it can stay separate, but you're right that it should just be in `__repr__` probably

for the two static methods: since both are only applied to `Taxon` classes, probably does make sense to put that as a method inside `Taxon`, will do deal with this after your PRs
